### ISSUE TITLE
deploy the backend

### ISSUE THREAD

**Issue by open-longlabs** [selfdevs/accountability-dashboard#34]
decide on deployment type (RPI, cloud, vps, heroku, ...) so the frontend can connect and manipulate the data with the DB

**Comment by cchampou** [comment]
We need to figure out what domain we want to use

**Comment by cchampou** [comment]
Database for preview is already hosted on Atlas for free.

**Comment by cchampou** [comment]
After verification, Atlas Free plan should be totally fine for first version. Export is possible anyway if we want to migrate later to some other platform.
For hosting, Heroku seems to be a good idea, free to start with, without credit card, and even if the hours are limited, we don't need to have it always on so could work. Also deployment is made really easy.

**Comment by probablyArth** [comment]
Isn't the dashboard deployed already?

**Comment by cchampou** [comment]
True
