### ISSUE TITLE
Form details are not cleared after submission

### ISSUE THREAD

**Issue by Juliotati** [selfdevs/accountability-dashboard#58]
- Unless it's the desired behavior I believe the filled-in fields should be cleared after successfully adding an entry.
## Demo preview
https://user-images.githubusercontent.com/59662912/149037157-12426e1d-4770-4bcd-bb53-0310338947f1.mp4

**Comment by M123-dev** [comment]
I'd rather go ahead and sync this with #55, in more detail a button which creates a new row directly in edit mode instead of the textfields at the bottom.

What do you think about that @cchampou @Juliotati

**Comment by cchampou** [comment]
> I'd rather go ahead and sync this with #55, in more detail a button which creates a new row directly in edit mode instead of the textfields at the bottom.
> 
> What do you think about that @cchampou @Juliotati

Go for it for sure !!

**Comment by Juliotati** [comment]
> I'd rather go ahead and sync this with #55, in more detail a button which creates a new row directly in edit mode instead of the textfields at the bottom.
> 
> What do you think about that @cchampou @Juliotati

🔥🚀 YES!!
