### ISSUE TITLE
Add confirmation before deleting an entry

### ISSUE THREAD

**Issue by cchampou** [selfdevs/accountability-dashboard#63]
## Current behavior

Currently when you click on the delete icon along an entry, it instantly destroys the line.

## Desired behavior

We want any kind of confirmation to prevent miss-click.

**Comment by probablyArth** [comment]
I'd like to pick this issue :)

**Comment by cchampou** [comment]
> I'd like to pick this issue :)

Sure man! I've assigned you to the task :)

**Comment by probablyArth** [comment]
I'hve implemented this, will push it with other changes.
