### ISSUE TITLE
User doesn't stay logged in after a while

### ISSUE THREAD

**Issue by ACT-06** [selfdevs/accountability-dashboard#83]

**Comment by Juliotati** [comment]
- #65 
Previously the timeout was increased to 12hrs as seen on the issue above, but I must say it's a bit too much having to log in again after a while.

@duytrann @longinteger017 @cchampou What do you think about increasing the timeout to a week?

**Comment by open-longlabs** [comment]
I also would confirm increasing the timeout time

**Comment by cchampou** [comment]
Ok to increase to 1 week. I take the ticket.
Although we really need to improve security / reliability of the auth system.

**Comment by cchampou** [comment]
Token expiration is now 1 week. Will be effective on your next token generation, so next time you login. You can logout to do it now.

**Comment by cchampou** [comment]
If the solution is good for you, you can close this ticket :)

**Comment by ACT-06** [comment]
I like the token expiration 1 week, but is there a possibility that the token can be recreated / refreshed whenever you come back within that week?

**Comment by cchampou** [comment]
Yes there is, need so more complex development though, thus the "Although we really need to improve security / reliability of the auth system.". 
Quite busy so not sure whenever I would have the time to do this, otherwise, anyone wanting to develop an refresh system can assign himself on the ticket ;)

**Comment by Juliotati** [comment]
1 week expiration seems fine for now, after the security concerns are addressed we can always make it better🔥

**Comment by probablyArth** [comment]
I can do the system for refresh tokens, so if I'm right, this should be the flow:

- when we login we get auth_token and refresh_token
- we store refresh tokens
- Auth token has some expiry time
- when that happens we send a request to backend to generate a new auth token from refresh token with same expiry time.
- In the backend we check if that refresh_token is stored in our db.
- If so, we grant new auth_token.
- When they logout they send refesh_token in body and we remove that refresh_token from our db.

Probably should use redis, but will that be too much?

**Comment by cchampou** [comment]
You got this @ArthThapa !
Redis is not **necessary** given the very low traffic of the site. Although you can if you want to :)
